import type { Metadata } from 'next'
import { Libre_Franklin } from 'next/font/google'
import '@/styles/globals.css'
import Header from '@/components/shared/header'
import Footer from '@/components/shared/footer'

const Libre = Libre_Franklin({ subsets: ['latin'],style:['normal','italic'],variable:"--font-libre-franklin" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Libre.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
